query readUser($id: UUID!) {
  _entities(representations: [{__typename: "GroupGQLModel", id: $id}]) {
		...GroupModel
  }
}

fragment GroupModel on GroupGQLModel {
  __typename
  id
  events {
    ...EventModel
  }
}

fragment EventModel on EventGQLModel {
  __typename
  id
  lastchange
  name
  startdate
  enddate
  duration(unit: MINUTES)
  description
  placeId
  eventType { id name }
  masterEvent { id name }
  subEvents { id name }
}
