mutation($group_id: UUID!, $event_id: UUID!) {
  result: eventGroupDelete(eventGroup: {
    groupId: $group_id, eventId: $event_id
  }) {
    id
    msg
    result: event {
      lastchange
      id
      name
      groups { id }
    }
  }
}