mutation ($id: UUID!, $lastchange: DateTime!, $name: String!, $name_en: String) {
  result: eventPresenceTypeUpdate(
    presenceType: {id: $id, lastchange: $lastchange, name: $name, nameEn: $name_en}
  ) {
    id
    msg
    result:  presenceType{
      ...EventPresenceType
    }
  }
}

fragment EventPresenceType on PresenceTypeGQLModel {
  __typename
  lastchange
  id
  name
  nameEn
  
  created
  createdby { id }
  changedby { id }
  
}