
mutation($id: UUID!, $lastchange: DateTime!, $valid: Boolean, $startdate: DateTime, $enddate: DateTime ) {
  result: membershipUpdate(membership: {id: $id, lastchange: $lastchange, valid: $valid, startdate: $startdate, enddate: $enddate}) {
    id
    msg
    result: membership {
      id
      lastchange
    }
  }
}