mutation formTypeUpdate($id: UUID!, $lastchange: DateTime!, $name: String) {
  result: formItemTypeUpdate(itemType: {id: $id, lastchange: $lastchange, name: $name}) {
    id
    msg
    result: itemType{
      ...FormItemTypeModel
    }
  }
}

fragment FormItemTypeModel on FormItemTypeGQLModel {
  __typename
  id
  lastchange
  name
  created
  createdby { id }
  changedby { id }
  rbacobject { id }
}