mutation statemachineUpdate($id: UUID!, $lastchange: DateTime!, $name: String!, $name_en: String) {
  result: statemachineUpdate(
    statemachine: {id: $id, lastchange: $lastchange, name: $name, nameEn: $name_en}
  ) {
    id
    msg
    result: statemachine {
      ...StatemachineModel
    }
  }
}


fragment StatemachineModel on StateMachineGQLModel {
  __typename
  lastchange
  id
  name
  states {
    __typename
    id
    name
    sources {
      id
      name
      source {
        id
        name
      }
    }
    targets {
      id
      name
      target {
        id
        name
      }
    }
  }
  transitions {
    id
    name
  }
  created
  createdby {
    id
  }
  changedby {
    id
  }
}