
query QuestionPage($skip: Int = 0, $limit: Int = 10, $where: QuestionInputWhereFilter) {
  result: questionPage(skip: $skip, limit: $limit, where: $where) {
    ...Question
  }
}

fragment Question on QuestionGQLModel {
  __typename
  id
  lastchange
  
  name
  order
  type { id name }
	survey { id name }
  answers { id }
  created
  createdby { id fullname }
  changedby { id fullname }  
  
}