query formById($id: UUID!) {
  formById(id: $id) {
    ...FormModel
  }
}

fragment FormModel on FormGQLModel {
  __typename
  id
  lastchange
  name
  sections {
    id name
  }
  
  created
  createdby { id }
  changedby { id }
  rbacobject { id }
}