mutation statetransitionUpdate(
  $id: UUID!, $lastchange: DateTime!, $name: String,
  $source_id: UUID, $target_id: UUID
) {
  result: statetransitionUpdate(
    statetransition: {id: $id, lastchange: $lastchange, name: $name
      sourceId: $source_id, targetId: $target_id
    }) {
    id
    msg
    result: statetransition{
    	...StateTransitionModel
  	}
    statemachine { id }
  }
}

fragment StateTransitionModel on StateTransitionGQLModel {
  __typename
  id
  name
  source { id name }
  target { id name }
  
  lastchange
  created
  createdby {
    id
  }
  changedby {
    id
  }
  statemachine { id name }
}