mutation (
  $id: UUID!, $lastchange: DateTime!, $value: String, $aswered: Boolean, $expired: Boolean ) {
  result: answerUpdate(
    answer: {
      id: $id, lastchange: $lastchange, value: $value, aswered: $aswered, expired: $expired
    }) {
    id
    msg
    result: answer {
      ...Answer
    }
  }
}

fragment Answer on AnswerGQLModel {
  __typename
  id
  lastchange

  value
  aswered
  expired
  user { id }
  question { id name }
  
  created
  createdby { id fullname }
  changedby { id fullname }  
  
}