
mutation ($id: UUID!, $lastchange: DateTime!, $startdate: DateTime, $enddate: DateTime, $name: String, $type_id: UUID, $masterevent_id: UUID) {
  result: eventUpdate(
    event: {id: $id, lastchange: $lastchange, startdate: $startdate, enddate: $enddate, name: $name, typeId: $type_id, mastereventId: $masterevent_id}
  ) {
    id
    msg
    result: event {
      id
      lastchange
    }
  }
}        
