query ($skip: Int, $limit: Int, $where: RequestWhereFilter) {
  result: requestPage(skip: $skip, limit: $limit, where: $where) {
    ...RequestModel
  }
}


fragment RequestModel on RequestGQLModel {
  __typename
  id
  lastchange
  name
  nameEn
  form { id name }
  state { id }
  histories {
    id
    name
    form {
      id
    }
  }
  created
  changedby {
    id
  }
  createdby {
    id
  }
  creator {
    id
  }
  rbacobject {
    id
  }
}