mutation stateInsert($id: UUID, $name: String!, $statemachine_id: UUID!) {
  result: stateInsert(state: {id: $id, name: $name, statemachineId: $statemachine_id}) {
    id
    msg
    result: state{
    	...State
  	}
    statemachine { id }
  }
}


fragment State on StateGQLModel {
  __typename
  id
  name
  
  lastchange
  created
  createdby {
    id
  }
  changedby {
    id
  }
  statemachine { id name }
}