mutation formCategoryInsert($id: UUID, $name: String!) {
  result: formItemCategoryInsert(itemCategory: {id: $id, name: $name}) {
    id
    msg
    result: category{
      ...FormItemCategoryModel
    }
  }
}

fragment FormItemCategoryModel on FormItemCategoryGQLModel {
  __typename
  id
  lastchange
  name
  created
  createdby { id }
  changedby { id }
  rbacobject { id }
}